name: flews
description: A Hacker News client written in Flutter

dependencies:
  flutter:
    sdk: flutter
  share: ^0.2.1
#  shared_preferences: ^0.2.0+1
  url_launcher: ^0.4.2+5
  meta: ^1.0.4
  built_value: ^4.2.0
  built_collection: ^1.0.0
  rxdart: 0.11.0
  intl: 0.15.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build: ^0.10.0
  build_runner: '>=0.4.0'
  built_value_generator: ^4.2.0
  mockito: 2.2.0
  source_gen: ^0.7.0

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section here, in
  # this "flutter" section, as in:
  assets:
    - images/icons/ycombinator.png
    - images/icons/reddit.png
    - images/icons/imgur.png
    - images/icons/github.png

  # To add assets from package dependencies, first ensure the asset
  # is in the lib/ directory of the dependency. Then,
  # refer to the asset with a path prefixed with
  # `packages/PACKAGE_NAME/`. Note: the `lib/` is implied, do not
  # include `lib/` in the asset path.
  #
  # Here is an example:
  #
  # assets:
  #  - packages/PACKAGE_NAME/path/to/asset

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
